global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
